### PR TITLE
Add error codes to StitchingError

### PR DESCRIPTION
**Pull request by Luthics**
I distinguish the error and warning in the program in detail, so that my program can accurately capture errors and warnings and give feedback to the user.

Even though I don't change anything, unittest still throws an error and I don't know why.

**This PR adds:**
Errors:
- CameraAdjustmentError
- InvalidMaskIndexError
- InvalidArgumentError
- NoMatchExceedsThresholdError
- HomographyEstimationError
- InvalidContourError
- RectanglesNotOverlapError
- ResolutionMismatchError
- InsufficientImagesError
- ImageReadError

Warnings:
- IdenticalColorsWarning
- ImagesNotFullIncludedWarning

### CODE REVIEW

**Comment by lukasalexanderweber** [comment]
you mean that you need more detailed information on where a StitchingError/Warning occur?

**Comment by Luthics** [comment]
> you mean that you need more detailed information on where a StitchingError/Warning occur?

yeah.

I want to use stitching as the backend of an image processing website, so I want to capture more detailed errors and warnings for user feedback.

**Comment by lukasalexanderweber** [comment]
while I understand that this information is important, I don't like the idea of creating a new Error for each possible exception.
We could maybe introduce error codes so you know better what failed as e.g. in https://stackoverflow.com/questions/6180185/custom-python-exceptions-with-error-codes-and-error-messages

**Comment by Luthics** [comment]
> while I understand that this information is important, I don't like the idea of creating a new Error for each possible exception. We could maybe introduce error codes so you know better what failed as e.g. in https://stackoverflow.com/questions/6180185/custom-python-exceptions-with-error-codes-and-error-messages

Compared to create a new Error for each possible exception, using error code is more elegant, I will optimize my code.

I'm a beginner, thanks for your advice!!!

**Comment by lukasalexanderweber** [comment]
@Luthics are you still working this or can we close the PR?

**Comment by Luthics** [comment]
> @Luthics are you still working this or can we close the PR?

I'm sorry for taking up so long, my college has started, there are more things, I try to finish it in this week.

**Comment by lukasalexanderweber** [comment]
We don't really need this, so just continue if its important to you

**Pull request closed without merging**
