### PR TITLE
Add masking for feature detection

### PR DESCRIPTION
**Pull request by 3nol**
I created this PR as a follow-up for [PR#55](https://github.com/OpenStitching/stitching/pull/55) since no further progress has been made. I based my implementation on @piercus's attempt, so he receives partial credit.

I only implemented the first part of the above PR (feature masking, not background stitching etc.). But I think this is already very helpful for stitching.

This PR adds:
- The `--masks` cli parameter (as mentioned, only feature masks for now)
- Change to the `ImageHandler` to allow storing mask file names, as well as corresponding accessors
- An additional test for feature masking in `test_detector.py`

### CODE REVIEW

**Comment by lukasalexanderweber** [comment]
Thanks for keeping up on this! I'm leaving into holiday and need some time to review this, I hope its fine that I check back to you when I'm back.

**Comment by lukasalexanderweber** [comment]
During the review of the PR I noticed that the ImageHander has too much state and so a bug (https://github.com/OpenStitching/stitching/commit/817c3d01b6784e1de319189f5b6606633d17f806). I would like to refactor/fix this first, because I think that then not so much code has to be inserted into the image handler, which is already too complicated for my taste. I hope this is fine for you.

**Comment by lukasalexanderweber** [comment]
what would be helpful in the meantime is a test where the full stitching worklow is run with and without feature masks and we see that different results are achieved. You could place the images [here](https://github.com/OpenStitching/stitching_tutorial/tree/master/imgs), we could then present the feature in the tutorial and download it from there for out tests.

**Comment by 3nol** [comment]
Thanks for looking into this again! Yes, that sounds like a good idea. After all, using masks is a very user-facing feature, and a tutorial with working examples might be very helpful.

I will add a test with the full stitching workflow (and example images) in the next couple days.

**Pull request closed without merging**
